package com.example.avengersapp.repository

import com.example.avengersapp.model.AvengerCharacter
import com.example.avengersapp.model.AvengerCharacters

object AvengerCharactersRepository {

    val charactersHeroes: AvengerCharacters
    get () {
        return arrayListOf(
            AvengerCharacter("thanos", "Thanos", "Interpretado por Josh Brolin (Cable en ‘Deadpool 2’), Thanos es el malo malísimo. Pero uno con carisma y cierto encanto. Es un alienígena color morado del planeta Titán obsesionado con reducir la población de todos los planetas en un 50%, nada más y nada menos, para erradicar la sobrepoblación que trae el hambre a uno y otro lado de la galaxia."),
            AvengerCharacter("nick", "Nicholas Fury", "Furia es el cerebro y fundador de los Vengadores. Es un guerrero de élite que apareció por primera vez en el cómic ‘Sgt. Fury y sus Comandos Aulladores # 1‘ (mayo de 1963). Es un personaje creado por Jack Kirby y Stan Lee (como la mayoría), jefe de la agencia secreta S.H.I.E.L.D. y la persona que vela por la supervivencia de nuestro planeta. Su personaje está interpretado por el magnífico Samuel L. Jackson… Aunque en ‘Endgame’ está convertido en polvo."),
            AvengerCharacter("capitana_marvel", "Capitana Marvel", "Interpretada por Brie Larson (‘Kong: La isla Calavera’), Carol es una piloto de la Fuerza Aérea de los Estados Unidos que busca recuperar sus recuerdos de la infancia. También es una guerrera del Imperio Kree y una súper humana que, gracias a la ayuda de Nick Furia, es un elemento decisivo para vencer a Thanos. Una última esperanza que nadie conocía antes de ‘Vengadores: Infinity War’."),
            AvengerCharacter("iron_man", "Iron Man", "Interpretado por Robert Downey Jr. (‘Sherlock Holmes’), Tony es un caprichoso multimillonario y genio inventor de la inteligencia artificial Jarvis. Es el heredero de Stark Industries y de una tecnología revolucionaria que aplica en su propio traje."),
            AvengerCharacter("hulk", "Hulk", "Interpretado por Mark Ruffalo (‘Zodiac’), Banner es un brillante científico bioquímico y experto en física molecular. También es un gigante verde de fuerza desconocida cuando se enfada. A lo largo de las distintas películas se ha visto dominado por una de las dos personalidades. Si alguna vez hace daño a sus compañeros es por pura accidentalidad. Es un cacho de pan y un buen amigo de Stark."),
            AvengerCharacter("cap_america", "Capitán América", "Interpretado por Chris Evans (‘Los 4 fantásticos’), Rogers era un soldado flacucho de corazón puro en la Segunda Guerra Mundial que, a través de un suero especial, terminó convertido en una especie de súper guerrero. Una ventaja decisiva con la que logran combatir y vencer a las tropas del villano Red Skull, un nazi que planeaba gobernar el planeta entero."),
            AvengerCharacter("thor", "Thor", "El dios del trueno interpretado por el actor australiano Chris Hemsworth (‘Star Trek’) fue uno de los últimos vengadores del equipo, pero también uno de los más poderosos. Fue desterrado de su tierra natal, Asgard y hechizado por las artes oscuras de su hermano Loki, interpretado por un sobresaliente Tom Hiddleston."),
            AvengerCharacter("ojo_halcon", "Ojo de Halcón", "Interpretado por Jeremy Renner (‘Wind River’), Ojo de Halcón no tiene poderes ni lanza rayos, pero es un magnífico soldado y donde pone el ojo, pone la flecha. Fue durante años el hombre de confianza de Nick Furia, en calidad de agente de S.H.I.E.L.D., pero terminó distanciándose del equipo en aras de conciliar una vida familiar."),
            AvengerCharacter("viuda_negra", "Viuda Negra", "Interpretado por Scarlett Johansson (‘Lucy’), el personaje de Natasha tampoco cuenta con habilidades especiales aunque es una magnífica combatiente, dominando artes marciales, combate táctico e infiltración. Fue una bailarina profesional y es la única persona capaz de calar a Bruce Banner cuando se transforma en Hulk. Un vínculo romántico que no dura mucho, por desgracia."),
        )
    }

    val charactersVillains: AvengerCharacters
    get () {
        return arrayListOf(
            AvengerCharacter("bruja_escarlata", "Bruja Escarlata", "Quién sí desarrolla interesantes habilidades es Wanda, interpretada por Elizabeth Olsen (‘Luces rojas’) y capaz de controlar objetos telepáticamente. Ella y su hermano desarrollaron habilidades especiales debido a una explosión. Más tarde, Wanda mantendrá una relación romántica con Jarvis, pero no con el robot, sino con su nueva versión de cuerpo humano denominada Visión, interpretado por Paul Bettany. Juntos forman un poderosísimo tándem."),
            AvengerCharacter("spider_man", "Spider-Man", "¿Quién no conoce a Spiderman? Aunque esta sea su enésima iteración, la versión interpretada por Tom Holland (‘Lo imposible’) supone un perspicaz ejercicio de síntesis de este carismático personaje. Para los novatos: una araña le picó y, desde entonces, desarrolló ciertas habilidades como la capacidad de adherirse a las paredes o superfuerza. En ‘Civil War’ tomará partido y se unirá al equipo Avengers."),
            AvengerCharacter("ant_man", "Ant-Man", "Interpretado por Paul Rudd (‘El reportero’), como en otras películas de Marvel, a Ant-Man lo conocimos en una película propia donde pasó de ladrón especializado en cajas fuertes a importante guerrero con un traje que le concede la propiedad de reducir su tamaño hasta hacerse tan pequeño como una hormiga."),
            AvengerCharacter("doctor_strange", "Doctor Strange", "El de Strange es uno de los personajes más interesantes de todo el Universo Marvel. Su historia nace de un virtuoso cirujano que busca rehabilitarse tras un grave accidente. En su búsqueda por Nepal es educado en artes místicas y termina convertido en el Hechicero Supremo, capaz de congelar el tiempo y viajar a distintos universos alternativos."),
            AvengerCharacter("bucky", "Bucky Burners", "Interpretado por Sebastian Stan (‘Yo, Tonya’), fue entrenado como soldado en la Segunda Guerra Mundial junto a su mejor amigo Steve Rogers, quien lo dio por muerto durante generaciones. Él también es un guerrero especial con brazo biónico y el elemento clave que desatará la guerra civil entre Capitán América e Iron Man. Pero su corazón es verdaderamente noble y aunque el Soldado de Invierno nunca ha sido considerado un vengador, ayudará en la batalla final."),
            AvengerCharacter("star_lord", "Star-Lord", "Este carismático personaje interpretado por Chris Pratt (‘Parks & Recreation’) es hijo de un dios y de una terrícola. Además de su descacharrante arco romántico con Gamora, es el líder de los Guardianes de la Galaxia, un comando de cazarrecompensas que surcan las estrellas. Reconvertidos en salvadores universales, su equipo está formado por Rocket, el furioso mapache super inteligente interpretado por Bradley Cooper (‘Ha nacido una estrella’); Groot, el extraterrestre de aspecto similar a un árbol humanoide que solo pronuncia su nombre; Drax ‘El Destructor’, un poderoso guerrero interpretado por Dave Bautista, y la propia Gamora."),
            AvengerCharacter("gamora_nebula", "Gamora y Nebula", "¿Y quién es Gamora? Un personaje importantísimo. Es la hija de Thanos y hermanastra de Nebula —interpretada por Karen Gillan (‘Jumanji: Bienvenidos a la Jungla’)—. Zoe Saldana (‘Avatar’) da vida a este potente personaje femenino que vivió de primera mano la ira de Thanos, cuando este sacrificó a su raza en una de sus salvajes escaramuzas."),
            AvengerCharacter("black_panther", "Black Panther", "Y cerramos con uno de los personajes más interesantes de todo el Universo Marvel, el último vengador por estricto orden cronológico: Black Panther. Interpretado por Chadwick Boseman (‘Get on Up’), él es el Rey de Wakanda tras la muerte de su padre y, como heredero de un reino, debe cuidar de los suyos.")
        )
    }

}